#!/bin/sh

# Check if this is the master device
grep "^ismaster=yes" /var/raumfeld-1.0/master-process.conf || exit 0

# Check for disk label
label=$(blkid -o value -s LABEL $UM_DEVICE)

if test "$label" = "STREAMDUMP"; then
  mkdir -p /tmp/streamdump
  mount --bind $UM_MOUNTPOINT /tmp/streamdump
  mount -o remount,rw,flush /tmp/streamdump
fi
