#!/bin/sh

# Check if this is the master device
grep "^ismaster=yes" /var/raumfeld-1.0/master-process.conf || exit 0

# Check for disk UUID and label
uuid=$(blkid -o value -s UUID $UM_DEVICE)
label=$(blkid -o value -s LABEL $UM_DEVICE)

if test -z "$label"; then
  # If there's no label, use vendor and/or model

  if test -n "$UM_VENDOR"; then
    label="$UM_VENDOR $UM_MODEL"
  elif test -n "$UM_MODEL"; then
    label="$UM_MODEL"
  else
    label="USB Storage"
  fi
fi

i=3
while [ $i -gt 0 ]; do
    /usr/bin/raumfeld-prefs \
        "set-value /Preferences/Storages Storage $uuid Path file://$UM_MOUNTPOINT" \
        "set-value /Preferences/Storages Storage $uuid Online yes" \
        "set-value /Preferences/Storages Storage $uuid Name $label" \
        "store" && break
    i=`expr $i - 1`
    echo "raumfeld-prefs failed. Trying $i more times."
done
