#!/bin/sh
#

case "$1" in
  start)
	connmanctl enable wifi
	sleep 1
        # TODO: pick wlan frequency via select-wlan-channel
	connmanctl tether wifi on 'RaumfeldNewSetup' '' 2452 lone-ap
	
	cd /raumfeld/raumfeld-setup
	./raumfeld-setup --verbose &
	;;
  *)
        ;;
esac

exit $?
