#!/bin/sh
#
# This script waits until $INTERFACE is up and running and reduces its
# transmit power, in order to comply with international standards
#

case "$1" in
	start)
		/raumfeld/wlan0-txpower-fixup.sh &
	;;
	*)
		echo "Usage: $0 {start}"
		exit 1
	;;
esac

exit $?
