#############################################################
#
# linux-config
#
#############################################################

define RAUMFELD_LINUX_CONFIG_ENABLE_BRIDGE
	$(call KCONFIG_ENABLE_OPT,CONFIG_BRIDGE,$(1))
endef

define RAUMFELD_LINUX_CONFIG_DISABLE_BRIDGE_IGMP_SNOOPING
	$(call KCONFIG_DISABLE_OPT,CONFIG_BRIDGE_IGMP_SNOOPING,$(1))
endef

define RAUMFELD_LINUX_CONFIG_ENABLE_SND_USB
	$(call KCONFIG_ENABLE_OPT,CONFIG_SND_USB,$(1))
endef

define RAUMFELD_LINUX_CONFIG_ENABLE_SND_USB_AUDIO
	$(call KCONFIG_SET_OPT,CONFIG_SND_USB_AUDIO,m,$(1))
endef

ifeq ($(BR2_RAUMFELD_LINUX_CONFIG_BRIDGE),y)
LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_BRIDGE
LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_DISABLE_BRIDGE_IGMP_SNOOPING
endif

ifeq ($(BR2_RAUMFELD_LINUX_CONFIG_USB_AUDIO),y)
LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_SND_USB
LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_SND_USB_AUDIO
endif
