#############################################################
#
# linux-config
#
#############################################################

define RAUMFELD_LINUX_CONFIG_ENABLE_BRIDGE
	$(call KCONFIG_ENABLE_OPT,CONFIG_BRIDGE,$(1))
endef

define RAUMFELD_LINUX_CONFIG_DISABLE_BRIDGE_IGMP_SNOOPING
	$(call KCONFIG_DISABLE_OPT,CONFIG_BRIDGE_IGMP_SNOOPING,$(1))
endef

define RAUMFELD_LINUX_CONFIG_ENABLE_SND_USB
	$(call KCONFIG_ENABLE_OPT,CONFIG_SND_USB,$(1))
endef

define RAUMFELD_LINUX_CONFIG_ENABLE_SND_USB_AUDIO
	$(call KCONFIG_SET_OPT,CONFIG_SND_USB_AUDIO,m,$(1))
endef

define RAUMFELD_LINUX_CONFIG_ENABLE_ATH9K_HTC
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211,m,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_ATH_CARDS,$(1))
	$(call KCONFIG_SET_OPT,CONFIG_ATH9K_HTC,m,$(1))
	$(call KCONFIG_DISABLE_OPT,CONFIG_ATH9K_BTCOEX_SUPPORT,$(1))
endef

define RAUMFELD_LINUX_CONFIG_ENABLE_MWIFIEX_SDIO
	$(call KCONFIG_SET_OPT,CONFIG_MWIFIEX,m,$(1))
	$(call KCONFIG_SET_OPT,CONFIG_MWIFIEX_SDIO,m,$(1))
endef

define RAUMFELD_LINUX_CONFIG_DISABLE_MWIFIEX_SDIO
	$(call KCONFIG_DISABLE_OPT,CONFIG_MWIFIEX,$(1))
	$(call KCONFIG_DISABLE_OPT,CONFIG_MWIFIEX_SDIO,$(1))
endef

define RAUMFELD_LINUX_CONFIG_ENABLE_RT2800USB_RT55XX
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211,m,$(1))
	$(call KCONFIG_SET_OPT,CONFIG_RT2X00,m,$(1))
	$(call KCONFIG_SET_OPT,CONFIG_RT2800USB,m,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_RT2800USB_RT55XX,$(1))
endef

ifeq ($(BR2_RAUMFELD_LINUX_CONFIG_BRIDGE),y)
LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_BRIDGE
LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_DISABLE_BRIDGE_IGMP_SNOOPING
endif

ifeq ($(BR2_RAUMFELD_LINUX_CONFIG_USB_AUDIO),y)
LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_SND_USB
LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_SND_USB_AUDIO
endif

ifeq ($(BR2_RAUMFELD_LINUX_CONFIG_ATH9K_HTC),y)
LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_ATH9K_HTC
endif

ifeq ($(BR2_RAUMFELD_LINUX_CONFIG_MWIFIEX),y)
LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_MWIFIEX_SDIO
else
LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_DISABLE_MWIFIEX_SDIO
endif

ifeq ($(BR2_RAUMFELD_LINUX_CONFIG_RT2800USB_RT55XX),y)
LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_RT2800USB_RT55XX
endif
