#############################################################
#
# linux-config
#
#############################################################

define RAUMFELD_LINUX_CONFIG_ENABLE_BRIDGE
	$(call KCONFIG_ENABLE_OPT,CONFIG_BRIDGE,$(1))
endef

define RAUMFELD_LINUX_CONFIG_DISABLE_BRIDGE_IGMP_SNOOPING
	$(call KCONFIG_DISABLE_OPT,CONFIG_BRIDGE_IGMP_SNOOPING,$(1))
endef

define RAUMFELD_LINUX_CONFIG_ENABLE_INPUT_UINPUT
	$(call KCONFIG_SET_OPT,CONFIG_INPUT_UINPUT,m,$(1))
endef

define RAUMFELD_LINUX_CONFIG_ENABLE_SND_USB
	$(call KCONFIG_ENABLE_OPT,CONFIG_SND_USB,$(1))
endef

define RAUMFELD_LINUX_CONFIG_ENABLE_SND_USB_AUDIO
	$(call KCONFIG_SET_OPT,CONFIG_SND_USB_AUDIO,m,$(1))
endef

define RAUMFELD_LINUX_CONFIG_ENABLE_MWIFIEX
	$(call KCONFIG_SET_OPT,CONFIG_MWIFIEX,m,$(1))
endef

define RAUMFELD_LINUX_CONFIG_DISABLE_MWIFIEX
	$(call KCONFIG_DISABLE_OPT,CONFIG_MWIFIEX,$(1))
endef

define RAUMFELD_LINUX_CONFIG_ENABLE_MWIFIEX_SDIO
	$(call KCONFIG_SET_OPT,CONFIG_MWIFIEX_SDIO,m,$(1))
endef

define RAUMFELD_LINUX_CONFIG_DISABLE_MWIFIEX_SDIO
	$(call KCONFIG_DISABLE_OPT,CONFIG_MWIFIEX_SDIO,$(1))
endef

define RAUMFELD_LINUX_CONFIG_ENABLE_MWIFIEX_PCIE
	$(call KCONFIG_SET_OPT,CONFIG_MWIFIEX_PCIE,m,$(1))
endef

define RAUMFELD_LINUX_CONFIG_DISABLE_MWIFIEX_PCIE
	$(call KCONFIG_DISABLE_OPT,CONFIG_MWIFIEX_PCIE,$(1))
endef

define RAUMFELD_LINUX_CONFIG_ENABLE_RT2X00
	$(call KCONFIG_SET_OPT,CONFIG_MAC80211,m,$(1))
	$(call KCONFIG_SET_OPT,CONFIG_RT2X00,m,$(1))
endef

define RAUMFELD_LINUX_CONFIG_DISABLE_RT2X00
	$(call KCONFIG_DISABLE_OPT,CONFIG_RT2X00,$(1))
endef

define RAUMFELD_LINUX_CONFIG_ENABLE_RT2800USB_RT55XX
	$(call KCONFIG_SET_OPT,CONFIG_RT2800USB,m,$(1))
	$(call KCONFIG_ENABLE_OPT,CONFIG_RT2800USB_RT55XX,$(1))
endef

define RAUMFELD_LINUX_CONFIG_DISABLE_RT2800USB_RT55XX
	$(call KCONFIG_DISABLE_OPT,CONFIG_RT2800USB,$(1))
	$(call KCONFIG_DISABLE_OPT,CONFIG_RT2800USB_RT55XX,$(1))
endef

define RAUMFELD_LINUX_CONFIG_ENABLE_CIFS
	$(call KCONFIG_SET_OPT,CONFIG_CIFS,m,$(1))
endef

ifeq ($(BR2_RAUMFELD_LINUX_CONFIG_BRIDGE),y)
LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_BRIDGE
LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_DISABLE_BRIDGE_IGMP_SNOOPING
endif

ifeq ($(BR2_RAUMFELD_LINUX_CONFIG_INPUT_UINPUT),y)
LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_INPUT_UINPUT
endif

ifeq ($(BR2_RAUMFELD_LINUX_CONFIG_USB_AUDIO),y)
LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_SND_USB
LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_SND_USB_AUDIO
endif

ifeq ($(BR2_RAUMFELD_LINUX_CONFIG_MWIFIEX),y)
	LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_MWIFIEX
	ifeq ($(BR2_RAUMFELD_LINUX_CONFIG_MWIFIEX_SDIO),y)
		LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_MWIFIEX_SDIO
	else
		LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_DISABLE_MWIFIEX_SDIO
	endif

	ifeq ($(BR2_RAUMFELD_LINUX_CONFIG_MWIFIEX_PCIE),y)
		LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_MWIFIEX_PCIE
	else
		LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_DISABLE_MWIFIEX_PCIE
	endif
else
	LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_DISABLE_MWIFIEX
endif

ifeq ($(BR2_RAUMFELD_LINUX_CONFIG_RT2X00),y)
	LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_RT2X00
	ifeq ($(BR2_RAUMFELD_LINUX_CONFIG_RT2800USB_RT55XX),y)
		LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_RT2800USB_RT55XX
	else
		LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_DISABLE_RT2800USB_RT55XX
	endif
else
	LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_DISABLE_RT2X00
endif

ifeq ($(BR2_RAUMFELD_LINUX_CONFIG_CIFS),y)
LINUX_CONFIGURE_HOOKS += RAUMFELD_LINUX_CONFIG_ENABLE_CIFS
endif
