############################################################
#
# mcu-protocol
#
#############################################################

MCU_PROTOCOL_VERSION = $(call qstrip,$(BR2_PACKAGE_MCU_PROTOCOL_VERSION))
MCU_PROTOCOL_SITE = $(call qstrip,$(BR2_PACKAGE_MCU_PROTOCOL_REPOSITORY))
MCU_PROTOCOL_SITE_METHOD = git

ifeq ($(BR2_PACKAGE_MCU_PROTOCOL_ALSA_PLUGIN),y)
MCU_PROTOCOL_DEPENDENCIES = alsa-lib
endif


ifeq ($(BR2_PACKAGE_MCU_PROTOCOL_ALSA_PLUGIN),y)
define MCU_PROTOCOL_BUILD_ALSA_PLUGIN
	PATH=$(BR_PATH) $(MAKE) CROSS_COMPILE="$(TARGET_CROSS)" -C $(@D)
endef
define MCU_PROTOCOL_INSTALL_ALSA_PLUGIN
	PATH=$(BR_PATH) $(MAKE) CROSS_COMPILE="$(TARGET_CROSS)" \
		DESTDIR=$(TARGET_DIR) ALSAPLUGINDIR=/usr/lib/alsa-lib -C $(@D) install 
endef
endif

ifeq ($(BR2_PACKAGE_MCU_PROTOCOL_TOOLS),y)
define MCU_PROTOCOL_BUILD_TOOLS
	PATH=$(BR_PATH) $(MAKE) tools CROSS_COMPILE="$(TARGET_CROSS)" -C $(@D)
endef
define MCU_PROTOCOL_INSTALL_TOOLS
	PATH=$(BR_PATH) $(MAKE) CROSS_COMPILE="$(TARGET_CROSS)" DESTDIR=$(TARGET_DIR) -C $(@D) install-tools
endef
endif


define MCU_PROTOCOL_BUILD_CMDS
$(MCU_PROTOCOL_BUILD_ALSA_PLUGIN)
$(MCU_PROTOCOL_BUILD_TOOLS)
endef

define MCU_PROTOCOL_INSTALL_TARGET_CMDS
$(MCU_PROTOCOL_INSTALL_ALSA_PLUGIN)
$(MCU_PROTOCOL_INSTALL_TOOLS)
endef

$(eval $(generic-package))

mcu-protocol-dlclean:
	rm -f $(DL_DIR)/$(MCU_PROTOCOL_SOURCE)
