#!/bin/sh

# generate udev events for USB devices present at boot time

case "$1" in
    start)
        for uevent in $(find /sys -regex ".*\/block\/sd.*\/uevent"); do
            echo "add" > $uevent
        done
	;;
    *)
	;;
esac

exit $?
