#!/bin/sh

case "$1" in
  start)
    G_FILENAME_ENCODING="UTF-8,ISO-8859-1"

    DBUS_SERVICE=`dbus-launch --sh-syntax`
    echo $DBUS_SERVICE > /var/run/raumfeld.session
    eval $DBUS_SERVICE

    connmanctl enable wifi

    /raumfeld/master-process/start-master-process.sh &
    ;;
  *)
    ;;
esac

exit $?
