#!/bin/sh

case "$1" in
  start)
    G_FILENAME_ENCODING="UTF-8,ISO-8859-1"

    DBUS_SERVICE=`dbus-launch --sh-syntax`
    echo $DBUS_SERVICE > /var/run/raumfeld.session
    eval $DBUS_SERVICE
    export DBUS_SESSION_BUS_ADDRESS

    if [ -e /sys/module/mwifiex ]; then
        iw dev wlan0 interface add uap0 type __ap
    fi

    connmanctl enable wifi

    /raumfeld/raumfeld-setup/start-raumfeld-setup.sh &
    ;;
  *)
    ;;
esac

exit $?
