#!/bin/sh

Casex "$1" in
  start)
    iw dev wlan0 interface add uap0 type __ap
    connmanctl enable wifi

    echo "starting logger"
    mknod /var/run/raumfeld-setup-logger-pipe pipe
    logger -t "raumfeld" < /var/run/raumfeld-setup-logger-pipe &

    echo "starting raumfeld-setup"
    cd /raumfeld/raumfeld-setup
    ./raumfeld-setup --verbose > /var/run/raumfeld-setup-logger-pipe 2>&1 &
    ;;
  *)
    ;;
esac

exit $?
