#!/bin/sh

. ../tests.inc

echo "Press the SETUP button (1)."
$INPUT_TEST key_setup
echo "Press the RESET button (2)."
$INPUT_TEST key_f3
echo "Press the POWER button (3)."
$INPUT_TEST key_power
echo "done"

exit 0
