#!/bin/sh

. ../tests.inc
TITLE="AUDIOTEST"
DIALOGOPTS="--title $TITLE"
TESTOPTS=""

rm -f /tmp/out

killall arecord
killall aplay


if [ ! -z "$(grep AM33XX /proc/cpuinfo)" ]; then
    amixer cset numid=1 124
    TESTOPTS="-armada"
fi


/raumfeld/p0-audiotest/p0-audiotest ${TESTOPTS} 2>&1 | \
	tee /tmp/out | \
	/percent 216 | \
	dialog_progress "Testing audio loopback. Please wait." $DIALOGOPTS

if [ -z "$(grep ERROR /tmp/out)" ]; then
	dialog_success "OK!" $DIALOGOPTS
else
	dialog_err "TEST FAILED!" $DIALOGOPTS
	exit 1
fi

