#!/bin/sh

. ../tests.inc

# simple runtime dispatcher for different hardware types

hw=`cat /proc/cpuinfo | grep ^Hardware | cut -f 3 -d' '`

case "$hw" in
        Connector)
		./audio-loopback
		./spdif
		;;

        Speaker)
		./spdif
		;;

	*)
		dialog_info "Not doing any audio tests on hardware $hw" --title "AUDIOTEST"
		;;
esac

