#!/bin/sh

. ../tests.inc

killall arecord
killall aplay

amixer cset numid=1 122

(cd /raumfeld/factory-tests; ./audio-loopback)

if [ $? -eq 0 ]; then
        echo "success"
        exit 0
else
        exit 1
fi
