#!/bin/sh

. ../tests.inc
TITLE="BATTERY"
DIALOGOPTS="--title $TITLE"

SYSDIR=/sys/class/power_supply/ds2760-battery.0

CURRENT_IN_MIN=-400000
CURRENT_IN_MAX=-700000

check_charge() {
	current=$1
	voltage=$2

#
	charge_ok=1
}


if [ ! -d $SYSDIR ]; then
	dialog_err "BATTERY NOT CONNECTED" $DIALOGOPTS
	exit 1
fi

status=$(cat $SYSDIR/status)
if [ ! "$status" = "Charging" ]; then
	dialog_info "Power adapter is currently not connected. Please CONNECT power adapter now."
	
	while [ ! "$status" = "Charging" ]; do
		sleep 1
		status=$(cat $SYSDIR/status)
	done
fi

current=$(cat $SYSDIR/current_now)
voltage=$(cat $SYSDIR/voltage_now)

charge_ok=0
check_charge($current, $voltage)

if [ "$charge_ok" != "1" ]; then
	dialog_err "Reported values for charge (voltage: $voltage current: $current) is out of bounds"
	exit 1
fi

status=$(cat $SYSDIR/status)
if [ ! "$status" = "Discharging" ]; then
	dialog_info "Power adapter found. Please DISCONNECT power adapter now."

	while [ ! "$status" = "Discharging" ]; do
		sleep 1
		status=$(cat $SYSDIR/status)
	done
fi

current=$(cat $SYSDIR/current_now)
if [ $current -gt $CURRENT_IN_MIN ] || [ $current -lt $CURRENT_IN_MAX ]; then
	dialog_err "Reported current level for discharge ($current) is out of bounds"
	exit 1
fi

dialog_info "Please CONNECT power adapter again."

# use the power adapter wakeup logic to get back to life
suspend

dialog_success "OK!" $DIALOGOPTS

