#!/bin/sh

. ../tests.inc
TITLE="BATTERY"
DIALOGOPTS="--title $TITLE"

SYSDIR=/sys/class/power_supply/ds2760-battery.0

CURRENT_IN_MIN=-400000
CURRENT_IN_MAX=-700000

if [ ! -d $SYSDIR ]; then
	dialog_err "BATTERY NOT CONNECTED" $DIALOGOPTS
	exit 1
fi

status=$(cat $SYSDIR/status)
if [ ! "$status" = "Charging" ]; then
	if [ "$1" = "final" ]; then
		dialog_info "Please put the device to the docking station"
	else
		dialog_info "Power adapter is currently not connected. Please CONNECT power adapter now."
	fi

	while [ ! "$status" = "Charging" ]; do
		sleep 1
		status=$(cat $SYSDIR/status)
	done
fi

voltage=$(cat $SYSDIR/voltage_now)
max=3400000
min=4000000

if [ "$voltage" -lt "$min" ]; then
	dialog_err "Battery voltage too low ($voltage < $min). Please replace battery"
	exit 1
fi

if [ "$voltage" -gt "$max" ]; then
	dialog_err "Battery voltage too high ($voltage > $max). Please replace battery"
	exit 1
fi

current=$(cat $SYSDIR/current_now)
max=970000
min=420000

if [ "$current" -lt "$min" ]; then
	dialog_err "Charging current too low ($current < $low)"
	exit 1
fi

if [ "$current" -gt "$max" ]; then
	dialog_err "Charging current too high ($current > $max)"
	exit 1
fi


status=$(cat $SYSDIR/status)
if [ ! "$status" = "Discharging" ]; then
	if [ "$1" = "final" ]; then
		dialog_info "Please put the device OUT OF the docking station"
	else
		dialog_info "Power adapter found. Please DISCONNECT power adapter now."
	fi

	while [ ! "$status" = "Discharging" ]; do
		sleep 1
		status=$(cat $SYSDIR/status)
	done
fi

current=$(cat $SYSDIR/current_now)
if [ $current -gt $CURRENT_IN_MIN ] || [ $current -lt $CURRENT_IN_MAX ]; then
	dialog_err "Reported current level for discharge ($current) is out of bounds"
	exit 1
fi

#if [ ! "$1" = "final" ]; then
#	dialog_info "Please CONNECT power adapter again."
#
#	# use the power adapter wakeup logic to get back to life
#	suspend
#fi

dialog_success "OK!" $DIALOGOPTS

