#!/bin/sh

. ../tests.inc
TITLE="BATTERY"
DIALOGOPTS="--title $TITLE"

SYSDIR=/sys/class/power_supply/ds2760-battery.0

CURRENT_IN_MIN=-400000
CURRENT_IN_MAX=-700000

CURRENT_OUT_MIN=
CURRENT_OUT_MAX=

if [ ! -d $SYSDIR ]; then
	dialog_err "BATTERY NOT CONNECTED" $DIALOGOPTS
	exit 1
fi

status=$(cat $SYSDIR/status)
if [ ! "$status" = "Charging" ]; then
	dialog_info "Power adapter is currently not connected. Please CONNECT power adapter now."
	
	while [ ! "$status" = "Charging" ]; do
		sleep 1
		status=$(cat $SYSDIR/status)
	done
fi

current=$(cat $SYSDIR/current_now)
if [ $current -gt $CURRENT_OUT_MIN ] || [ $current -lt $CURRENT_OUT_MAX ]; then
	dialog_err "Reported current level for discharge ($current) is out of bounds"
	exit 1
fi

status=$(cat $SYSDIR/status)
if [ ! "$status" = "Discharging" ]; then
	dialog_info "Power adapter found. Please DISCONNECT power adapter now."

	while [ ! "$status" = "Discharging" ]; do
		sleep 1
		status=$(cat $SYSDIR/status)
	done
fi

current=$(cat $SYSDIR/current_now)
if [ $current -gt $CURRENT_IN_MIN ] || [ $current -lt $CURRENT_IN_MAX ]; then
	dialog_err "Reported current level for discharge ($current) is out of bounds"
	exit 1
fi

dialog_success "OK!" $DIALOGOPTS

