#!/bin/sh

set -e

echo "Mounting filesystem ..."

mount -t ubifs ubi:RootFS /mnt

echo "Copying files to flash. Please wait ..."

zcat /rootfs.tgz | tar -C /mnt -x
sync

echo "Unmounting filesystem ..."

umount /mnt
