#!/bin/sh

set -e

mount -t ubifs ubi:RootFS /mnt

cd /mnt
zcat /rootfs.tgz | tar -xv

# 'move' the uImage from the rootfs to its own partition
flash_erase /dev/mtd6 0 0
nandwrite --pad /dev/mtd6 boot/uImage
rm boot/uImage

cd /
umount /mnt

