#!/bin/sh

source ../tests.inc
TITLE="ETHADDR"
DIALOGOPTS="--title $TITLE"

dialog_info "Obtaining Ethernet MAC address. Please wait." $DIALOGOPTS

eval $(fw_printenv ethaddr)
if [ ! -z "$ethaddr" ]; then
	/sbin/ifconfig eth0 hw ether $ethaddr
	exit 0
fi

ethaddr=$(wget -q -O - http://$TEST_HOST_WIRELESS/cgi-bin/getmac)
test -z "$ethaddr" || exit -1

fw_setenv ethaddr $ethaddr
/sbin/ifconfig eth0 hw ether $ethaddr

exit 0

