#!/bin/sh

source ../tests.inc
TITLE="ETHERNET"
DIALOGOPTS="--title $TITLE"

/sbin/ifconfig eth0 ${IP_ETHERNET}

dialog_info "Testing ETHERNET. Please wait." $DIALOGOPTS

CRC1=$(wget -q -O - http://$TEST_HOST_ETHERNET/testimg.md5sum | cut -f1 -d' ')
CRC2=$(wget -q -O - http://$TEST_HOST_ETHERNET/testimg | md5sum | cut -f1 -d' ')

if [ "$CRC1" = "$CRC2" ]; then
	dialog_success "OK!" $DIALOGOPTS
	sleep 2
else
	dialog_err "TEST FAILED!" $DIALOGOPTS
	exit 1
fi

