#!/bin/sh

. ../tests.inc

ETH=eth0

echo "Testing ETHERNET. Please wait."
killall dhclient
ifconfig ${ETH} up
/usr/sbin/dhclient -sf /dhclient-script ${ETH}

# get default gw
set $(netstat -rn | grep ^0.0.0.0 | head -n 1)
GATEWAY=$2

if [ -z "$GATEWAY" ]; then
	echo "unable to obtain default gateway. FAIL!"
	exit 1
fi

ping -w 10 -c 5 -s 1000 $GATEWAY
RET=$?

ifconfig ${ETH} down

exit $RET
