#!/bin/sh

. ../tests.inc

/sbin/ifconfig eth0 ${IP_ETHERNET}

echo "Testing ETHERNET. Please wait."

CRC1=$(wget -q -T 2 -O - http://$TEST_HOST_ETHERNET/testimg.md5sum | cut -f1 -d' ')
CRC2=$(wget -q -T 2 -O - http://$TEST_HOST_ETHERNET/testimg | md5sum | cut -f1 -d' ')

if [ "$CRC1" = "$CRC2" ]; then
        echo "OK!"
else
        echo "TEST FAILED!"
        exit 1
fi

exit 0
