#!/bin/sh

. ../tests.inc

set -e

if is_model "Soundbar"; then
    MCU_FIRMWARE=/MCU/RaumfeldSoundbar.bin
elif is_model "Sounddeck"; then
    MCU_FIRMWARE=/MCU/RaumfeldSounddeck.bin
else
    echo "Model is not Soundbar nor Sounddeck"
    exit 1
fi

MCU_SERIAL_DEVICE=/dev/ttyO5

if [ -f $MCU_FIRMWARE ]; then
    echo "Flashing the MCU firmware ..."
    /usr/sbin/stm32flash -b 115200 -v -R -i 52,-51,51:-52,-51,51 -w $MCU_FIRMWARE $MCU_SERIAL_DEVICE
fi
