#!/bin/sh

. ../tests.inc
TITLE="HARDDISK"
DIALOGOPTS="--title $TITLE"

DEV=/dev/hda
TMPROOT=/tmp/root

# enable 32bit access
hdparm -c1 ${DEV}

# purge partition table, if any. This script does it the hard way.
dd if=/dev/zero of=$DEV bs=512 count=1

# create a new one
sfdisk $DEV << __EOF__
0,8
,300
;
;
__EOF__

for x in 1 2 3; do
	echo "****** Creating filesystem $x/3. ******"
	mkfs.ext3 ${DEV}${x}
done

mkdir $TMPROOT
mount -t ext3 ${DEV}2 $TMPROOT

echo "Mounting filesystems ..."

mkdir $TMPROOT/boot
mount -t ext3 ${DEV}1 $TMPROOT/boot

if [ -z "$(mount | grep $TMPROOT)" ]; then
	touch /tmp/hdd-failed
	exit
fi

echo "Copying files to harddisk. Please wait ..."

zcat /rootfs.tgz | tar -f - -C $TMPROOT -x
sync

if [ -f "/Raumfeld Demo.mp3" ]; then
    mkdir -p -m 755 $TMPROOT/data
    mount -t ext3 ${DEV}3 $TMPROOT/data
    mkdir -p -m 755 $TMPROOT/data/Music
    cp "/Raumfeld Demo.mp3" $TMPROOT/data/Music
    chown -R 99:99 $TMPROOT/data/Music
    umount $TMPROOT/data
fi

echo "Unmounting filesystems ..."

chmod 0755 $TMPROOT
umount $TMPROOT/boot
umount $TMPROOT

