#!/bin/sh

set -e

UBIDEV=0
UBIMTD=3
ROOT_SIZE=81MiB
UPDATE_SIZE=39MiB

# first, detach the volume attached by the kernel
# (and don't fail if it isn't attached for whatever reason)
ubidetach /dev/ubi_ctrl -d $UBIDEV || true

# erase the whole thing
ubiformat /dev/mtd3     

# re-attach the partition
ubiattach /dev/ubi_ctrl -d $UBIDEV -m $UBIMTD

# create the volume
ubimkvol /dev/ubi$UBIDEV -N RootFS -s $ROOT_SIZE
ubimkvol /dev/ubi$UBIDEV -N Updates -s $UPDATE_SIZE
