#!/bin/sh

set -e

UBIDEV=0
DTBMTD=7
UBIMTD=8
ROOT_SIZE=191MiB
UPDATE_SIZE=42MiB

# first, detach the volume attached by the kernel
# (and don't fail if it isn't attached for whatever reason)
ubidetach /dev/ubi_ctrl -d $UBIDEV || true

# erase the whole thing
flash_erase /dev/mtd$UBIMTD 0 0
ubiformat /dev/mtd$UBIMTD -s 512 -O 2048

# re-attach the partition
ubiattach /dev/ubi_ctrl -d $UBIDEV -m $UBIMTD -O 2048

# create the volume
ubimkvol /dev/ubi$UBIDEV -N RootFS -s $ROOT_SIZE
ubimkvol /dev/ubi$UBIDEV -N Updates -s $UPDATE_SIZE

# copy the DTB cramfs image to its home location
flash_erase /dev/mtd$DTBMTD 0 0
nandwrite --pad /dev/mtd$DTBMTD /dts.cramfs

