#!/bin/sh

. ../tests.inc

mode=$1

case "$mode" in
	1)
		while [ 0 ]; do
			led_off 0
			led_on  1
			led_off 2

			sleep 1

			led_on  0
			led_off 1
			led_on  2

			sleep 1
		done
		;;
	2)
		while [ 0 ]; do
			led_on 0
			led_on 1
			led_on 2

			sleep 1

			led_off 0
			led_off 1
			led_off 2

			sleep 1
		done
		;;
esac

