#!/bin/sh

. ../tests.inc

mode=$1

case "$mode" in
	1)
		while [ 0 ]; do
			led_off 1
			led_on  2
			led_off 3

			sleep 1

			led_on  1
			led_off 2
			led_on  3

			sleep 1
		done
		;;
	2)
		while [ 0 ]; do
			led_on 1
			led_on 2
			led_on 3

			sleep 1

			led_off 1
			led_off 2
			led_off 3

			sleep 1
		done
		;;
	3)
		while [ 0 ]; do
			led_on  1
			led_off 2
			led_off 3
			sleep 1
			led_off 1
			led_on  2
			led_off 3
			sleep 1
			led_off 1
			led_off 2
			led_on  3
			sleep 1
		done
		;;
	4)
		led_off 2
		led_off 3
		while [ 0 ]; do
			led_on 1
			sleep 1
			led_off 1
			sleep 1
		done
		;;
	5)
		led_off 1
		led_off 3
		while [ 0 ]; do
			led_on 2
			sleep 1
			led_off 2
			sleep 1
		done
		;;
	6)
		led_on 1
		led_off 2
		led_off 3
		while [ 0 ]; do
			led_on 2
			usleep 300000
			led_off 2
			usleep 300000
		done
		;;
	7)
		led_off 3
		while [ 0 ]; do
			led_on 2
			led_off 1
			usleep 300000
			led_on 1
			led_off 2
			usleep 300000
		done
		;;
	8)
		led_off 3
		while [ 0 ]; do
			led_on 1
			led_on 2
			usleep 100000
			led_off 1
			led_off 2
			usleep 100000
		done
		;;
	9)
		led_off 3
		while [ 0 ]; do
			led_on 1
			led_on 2
			usleep 100000
			led_off 1
			led_off 2
			usleep 100000
			led_on 1
			led_on 2
			usleep 100000
			led_off 1
			led_off 2
			sleep 1
		done
		;;
esac

