#!/bin/sh

source ../tests.inc
TITLE="WIRELESS"
DIALOGOPTS="--title $TITLE"

dialog_info "Testing WIRELESS. Please wait." $DIALOGOPTS

CRC1=$(wget -q -O - http://$TEST_HOST_WIRELESS/testimg.md5sum | cut -f1 -d' ')
CRC2=$(wget -q -O - http://$TEST_HOST_WIRELESS/testimg | md5sum | cut -f1 -d' ')

if [ "$CRC1" = "$CRC2" ]; then
	dialog_success "OK!" $DIALOGOPTS
	sleep 2
else
	dialog_err "TEST FAILED!" $DIALOGOPTS
	exit 1
fi

