#!/bin/sh

. ../tests.inc
TITLE="WIRELESS"
DIALOGOPTS="--title $TITLE"

source ./wifi.inc

/sbin/ifconfig ${WIRELESS_IFNAME} up
/sbin/iwconfig ${WIRELESS_IFNAME} mode Ad-Hoc
/sbin/iwconfig ${WIRELESS_IFNAME} essid ${ESSID}
/sbin/ifconfig ${WIRELESS_IFNAME} ${IP_WIRELESS}
sleep 2

dialog_info "Testing WIRELESS. Please wait. ---------------------------------- ESSID=$ESSID QUALITY=$QUALITY" $DIALOGOPTS

CRC1=$(wget -q -O - http://$TEST_HOST_WIRELESS/testimg.md5sum | cut -f1 -d' ')
CRC2=$(wget -q -O - http://$TEST_HOST_WIRELESS/testimg | md5sum | cut -f1 -d' ')

if [ "$CRC1" = "$CRC2" ]; then
	dialog_success "OK!" $DIALOGOPTS
else
	dialog_err "TEST FAILED!" $DIALOGOPTS
	exit 1
fi

