#!/bin/sh

. ../tests.inc
. ./wifi.inc

echo "ESSID: $ESSID"
echo "QUALITY: $QUALITY"

/sbin/ifconfig ${WIRELESS_IFNAME} down
/sbin/iwconfig ${WIRELESS_IFNAME} mode Ad-Hoc
/sbin/iwconfig ${WIRELESS_IFNAME} essid ${ESSID}
/sbin/ifconfig ${WIRELESS_IFNAME} ${IP_WIRELESS} up

/sbin/iwconfig ${WIRELESS_IFNAME} > /dev/tty1
/sbin/ifconfig ${WIRELESS_IFNAME} > /dev/tty1

