#!/bin/sh

. ../tests.inc

source ./wifi_armada.inc

/sbin/ifconfig ${WIRELESS_IFNAME} down
/sbin/iwconfig ${WIRELESS_IFNAME} mode Ad-Hoc
/sbin/iwconfig ${WIRELESS_IFNAME} essid ${ESSID}
/sbin/ifconfig ${WIRELESS_IFNAME} ${IP_WIRELESS} up
#sleep 2

echo "Testing WIRELESS. Please wait. ---------------------------------- ESSID=$ESSID QUALITY=$QUALITY"

#TODO: decrease timeout

CRC1=$(wget -T 10 -t 1 -q -O - http://$TEST_HOST_WIRELESS/testimg.md5sum | cut -f1 -d' ')
CRC2=$(wget -T 5 -t 1 -q -O - http://$TEST_HOST_WIRELESS/testimg | md5sum | cut -f1 -d' ')

if [ "$CRC1" = "$CRC2" ]; then
        echo "OK!"
else
        echo "TEST FAILED"
        exit 1
fi

exit 0



