#!/bin/sh

source ../tests.inc
TITLE="WIRELESS"
DIALOGOPTS="--title $TITLE"

source "wifi.inc"

if [ ${MIN_QUALITY} -gt ${QUALITY} ]; then
	dialog_err "SIGNAL LEVEL TOO WEAK"
	exit 1
fi

/sbin/ifconfig ${WIRELESS_IFNAME} up
/sbin/iwconfig ${WIRELESS_IFNAME} mode Ad-Hoc
/sbin/iwconfig ${WIRELESS_IFNAME} essid ${ESSID}
/sbin/ifconfig ${WIRELESS_IFNAME} ${IP_WIRELESS}
sleep 2

dialog_info "Testing WIRELESS. Please wait. ---------------------------------- ESSID=$ESSID QUALITY=$QUALITY" $DIALOGOPTS

CRC1=$(wget -q -O - http://$TEST_HOST_WIRELESS/testimg.md5sum | cut -f1 -d' ')
CRC2=$(wget -q -O - http://$TEST_HOST_WIRELESS/testimg | md5sum | cut -f1 -d' ')

if [ "$CRC1" = "$CRC2" ]; then
	dialog_success "OK!" $DIALOGOPTS
	sleep 2
else
	dialog_err "TEST FAILED!" $DIALOGOPTS
	sleep 2
	exit 1
fi

