#!/bin/sh

#TESTS MIDIFIED FOR MANAGED NETWORKS

. ../tests.inc
TITLE="WIRELESS-MANAGED"
DIALOGOPTS="--title $TITLE"

dialog_info "Testing WIRELESS in managed mode. Now scanning for RaumfeldFactoryTest"


source ./wifi_managed.inc

./leds-blink 6 &

TEST_HOST_WIRELESS=192.168.1.1

killall dhclient

/sbin/ifconfig ${WIRELESS_IFNAME} down
/sbin/iwconfig ${WIRELESS_IFNAME} mode Managed
/sbin/iwconfig ${WIRELESS_IFNAME} essid RaumfeldFactoryTest
/sbin/ifconfig ${WIRELESS_IFNAME} ${IP_WIRELESS} up
/usr/sbin/dhclient -sf /dhclient-script ${WIRELESS_IFNAME}


if [ ! -z "$(iwconfig ${WIRELESS_IFNAME} | grep -i Not-Associated)" ]; then
	err="can't connect to AP RaumfeldFactoryTest"
  dialog_err "$err"
  exit 1
fi


QUALITY=$(iwconfig ${WIRELESS_IFNAME} | grep -i "dBm" | cut -f3 -d= | cut -f1 -d' ')
MIN_QUALITY=-40

if [ ${MIN_QUALITY} -gt ${QUALITY} ]; then
	err="SIGNAL LEVEL $QUALITY TOO WEAK ($MIN_QUALITY required) -- ESSID $ESSID"
  dialog_err "$err"
  exit 1
fi



killall leds-blink

dialog_info "Testing WIRELESS. Please wait. ---------------------------------- ESSID=$ESSID QUALITY=$QUALITY" $DIALOGOPTS

./leds-blink 7 &

#TODO: decrease timeout

CRC1=$(wget -q -O - http://$TEST_HOST_WIRELESS/testimg.md5sum | cut -f1 -d' ')
CRC2=$(wget -q -O - http://$TEST_HOST_WIRELESS/testimg | md5sum | cut -f1 -d' ')

killall leds-blink

if [ "$CRC1" = "$CRC2" ]; then
	dialog_success "OK!" $DIALOGOPTS
  
else
	dialog_err "TEST FAILED!" $DIALOGOPTS
	exit 1
fi

