#!/bin/sh
#
# Setup Nonlinear Labs Ecosystem
#

start() {
        printf "Setup Nonlinear Labs Ecosystem...."
#	/usr/bin/setup.sh
}


stop() {
        printf "Setup Nonlinear Labs Ecosystem....Done"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
