#!/bin/sh

# this script is run once after an update from version 0.4.94 to 0.4.105

# check if we are upgrading from an affected version
if ! test -e /boot/bzImage; then
   # burn after reading
   rm /etc/init.d/S20update-fixup
   exit 0
fi

# kernel fixup
mount /dev/hda1 /mnt
mv /boot/bzImage /mnt
umount /mnt

# fix move from /Music to /data/Music
mkdir /data/Music
mv /data/* /data/Music
mv /data/Music/lost+found /data
sed -e 's|file:///Music|file:///data/Music|' /var/raumfeld-1.0/raumfeld-preferences.xml > /tmp/prefs && mv /tmp/prefs /var/raumfeld-1.0/raumfeld-preferences.xml

# burn after reading
rm /etc/init.d/S20update-fixup
reboot
