#!/bin/sh
#
# Start the bridging devices.
#

case "$1" in
  start)
 	echo "Setting up bridging devices..."
	brctl addbr br0
	brctl addif br0 eth0 
	brctl addif br0 wlan0
	brctl addif br0 eth1
	ifconfig eth0 up
	ifconfig eth1 up
	;;
  stop)
	echo -n "Stopping network..."
	brctl delif br0 eth0
	brctl delif br0 wlan0
	brctl delif br0 eth1
	ifconfig br0 down
	brctl delbr br0
	/sbin/ifdown -a
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

