#!/bin/sh
#
# Start the bridging devices.
#

case "$1" in
  start)
 	echo "Setting up bridging devices..."
	brctl addbr br0
	brctl addif br0 eth0 
	brctl addif br0 wlan0
	brctl addif br0 eth1
	ifconfig eth0 up
	ifconfig eth1 up
        hwaddr=$(ifconfig eth0 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}')
        ifconfig br0 hw ether $hwaddr
	ifconfig br0 up
	;;
  stop)
	echo -n "stopping bridge..."
	brctl delif br0 eth0
	brctl delif br0 wlan0
	brctl delif br0 eth1
	ifconfig br0 down
	ifconfig eth0 down
	ifconfig eth1 down
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

