#!/bin/sh
#
# Start hostapd....
#

case "$1" in
  start)
 	echo "Starting hostapd..."
	hostapd /etc/hostapd.conf -B
	;;
  stop)
	echo -n "Stopping hostpad..."
	killall hostapd
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

