#!/bin/sh

case "$1" in
  start)
       # change the mount options for the rootfs to noatime
       mount -o remount,noatime /

       # tweak settings of the internal hard-disk:
       # - limit DMA mode to UDMA2 (33 MB/s)
       # - enable power management
       # - set the standby (spindown) delay to 10 minutes
       hdparm -Xudma2 -B 128 -S 120 /dev/hda

       # start the setup process
       connmanctl enable wifi
       sleep 1
       # TODO: pick wlan frequency via select-wlan-channel
       connmanctl tether wifi on 'RaumfeldNewSetup' '' 2452 lone-ap

       cd /raumfeld/raumfeld-setup
       ./raumfeld-setup --verbose &
       ;;
  *)
       ;;
esac

exit $?
