#!/bin/sh

DEV_UUID=`LD_PRELOAD=libpthread.so.0 blkid $UM_DEVICE -s UUID | awk -F"\"" '{print $2}'`

# Check for disk label
label=`/lib/udev/vol_id --label $DEVPATH`

if test -z "$label"; then
  # If there's no label, use vendor and/or model

  if test -n "$UM_VENDOR"; then
    label="$UM_VENDOR $UM_MODEL"
  elif test -n " $UM_MODEL"; then
    label=" $UM_MODEL"
  else
    label="USB Storage"
  fi
fi

i=3
while [ $i -gt 0 ]; do
    /usr/bin/raumfeld-prefs \
        "set-value /Preferences/Storages Storage $DEV_UUID Path file://$UM_MOUNTPOINT" \
        "set-value /Preferences/Storages Storage $DEV_UUID Online 1" \
        "set-value /Preferences/Storages Storage $DEV_UUID Name $label" \
        "store" && break
    i=`expr $i - 1`
    echo "raumfeld-prefs failed. Trying $i more times."
done
