#!/bin/sh

uuid=`echo $UM_MOUNTPOINT | awk -F "/" '{print $3}'`

i=3
while [ $i -gt 0 ]; do
    /usr/bin/raumfeld-prefs \
        "set-value /Preferences/Storages Storage $uuid Online 0" \
        "store" && break
    i=`expr $i - 1`
    echo "raumfeld-prefs failed. Trying $i more times."
done
