#!/bin/sh
#
# Load modules ...
#

case "$1" in
  start)
 	echo "Loading modules..."
	modprobe pxamci

	modprobe snd-soc-adau1701
	modprobe snd-soc-ak4104
	modprobe snd-soc-ak5386
	modprobe snd-soc-cs4271
	modprobe snd-soc-sigmadsp
	modprobe snd-soc-tas5086
	modprobe snd-soc-davinci-mcasp
	# FIXME: the above modules should actually be implicitly loaded by the next one
        modprobe snd-soc-s800
	;;
  *)
	;;
esac

exit $?
